<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.samples</groupId>
        <artifactId>poc-jakarta-basic-saga</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sample-worker</artifactId>
    <packaging>war</packaging>
    <name>sample-worker</name>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.samples</groupId>
            <artifactId>jakarta-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.samples</groupId>
            <artifactId>jakarta-stream-binder-rabbit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.samples</groupId>
            <artifactId>jakarta-cqrs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.samples</groupId>
            <artifactId>jakarta-saga</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>sample-worker</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>${wildfly.plugin.version}</version>
                <configuration>
                    <bootable-jar>true</bootable-jar>
                    <discover-provisioning-info>
                        <version>${wildfly.version}</version>
                    </discover-provisioning-info>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>