<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>org.samples</groupId>
    <artifactId>poc-jakarta-basic-saga</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>poc-jakarta-basic-saga</name>

    <modules>
        <module>jakarta-stream-binder</module>
        <module>jakarta-cqrs</module>
        <module>sample-app</module>
        <module>sample-worker</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <jakarta.platform.version>10.0.0</jakarta.platform.version>
        <jackson.version>2.15.2</jackson.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <wildfly.plugin.version>5.1.5.Final</wildfly.plugin.version>
        <wildfly.version>38.0.0.Final</wildfly.version>
        <lombok.version>1.18.26</lombok.version>
        <slf4j.version>2.0.13</slf4j.version>
        <kafka.version>3.9.2</kafka.version>
        <rabbitmq.version>5.16.0</rabbitmq.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.samples</groupId>
                <artifactId>jakarta-stream-binder</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.samples</groupId>
                <artifactId>jakarta-cqrs</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>