messaging.channels.rabbit.host=localhost
messaging.channels.rabbit.port=5672
messaging.channels.rabbit.username=admin
messaging.channels.rabbit.password=admin

messaging.channels.kafka.bootstrap.servers=sample-kafka-broker:9092

# Productores
messaging.channels.creacion-expediente.type=rabbitmq
messaging.channels.creacion-expediente.exchange=expedientes
messaging.channels.creacion-expediente.routing-key=creacion-expediente

messaging.channels.creacion-expediente-alerta.type=kafka
messaging.channels.creacion-expediente-alerta.topic=creacion-expediente-alerta-topic

# Consumidores
messaging.channels.creacion-expediente-ok.type=rabbitmq
messaging.channels.creacion-expediente-ok.queue=creacion-expediente-ok-cola

messaging.channels.creacion-expediente-ko.type=rabbitmq
messaging.channels.creacion-expediente-ko.queue=creacion-expediente-ko-cola


