@startuml Secuencia creación expediente
title Secuencia creación expediente

skinparam sequence {
    ParticipantBackgroundColor #005b72
    ParticipantFontColor #ffffff
    ArrowColor #235872
    LifeLineBorderColor #005b72
    LifeLineBackgroundColor #005b72
}

participant "API Client" as Client
participant "API" as API
participant "API Event Dispatcher" as ApiEventDispatcher
participant "API Database" as ApiDB
participant "RabbitMQ" as Rabbit
participant "Kafka" as Kafka
participant "Worker" as Worker
participant "Worker Event Dispatcher" as WorkerEventDispatcher
participant "Worker Database" as WorkerDB

== Creación de expediente ==

Client -> API: POST /expedientes
activate Client
activate API
API -> ApiDB: Save expediente
activate ApiDB
ApiDB --> API: Saved
API -> ApiDB: Save outbox event
ApiDB --> API: Saved
deactivate ApiDB
API --> Client: 201 Created
deactivate API
deactivate Client

group Event Dispatching
    ApiEventDispatcher -> ApiDB: Fetch outbox events
    activate ApiEventDispatcher
    activate ApiDB
    ApiDB --> ApiEventDispatcher: Outbox events
    deactivate ApiDB
    ApiEventDispatcher -> Rabbit: Publish CreacionExpediente
    activate Rabbit
    Rabbit --> ApiEventDispatcher: Ack
    deactivate Rabbit
    ApiEventDispatcher -> ApiDB: Mark outbox event as processed
    activate ApiDB
    ApiDB --> ApiEventDispatcher: Updated
    deactivate ApiDB
    deactivate ApiEventDispatcher
end

== Crecion Expediente OK ==

Rabbit -> Worker: Evento expediente creado
activate Rabbit
deactivate Rabbit
activate Worker
Worker -> Worker: Ejecutar lógica de negocio
Worker -> WorkerDB: Save outbox event OK
activate WorkerDB
WorkerDB --> Worker: Saved
deactivate WorkerDB
deactivate Worker

group Event Dispatching
    WorkerEventDispatcher -> WorkerDB: Fetch outbox events
    activate WorkerEventDispatcher
    activate WorkerDB
    WorkerDB --> WorkerEventDispatcher: Outbox events
    deactivate WorkerDB
    WorkerEventDispatcher -> Rabbit: Publish Created OK
    activate Rabbit
    Rabbit --> WorkerEventDispatcher: Ack
    WorkerEventDispatcher -> WorkerDB: Mark outbox event as processed
    activate WorkerDB
    WorkerDB --> WorkerEventDispatcher: Updated
    deactivate WorkerEventDispatcher
    deactivate WorkerDB
end

Rabbit -> API: Evento expediente creado OK
deactivate Rabbit
activate API
API -> ApiDB: Actualizar estado
activate ApiDB
ApiDB --> API: Updated
deactivate ApiDB
deactivate API

== Crecion Expediente KO ==

Rabbit -> Worker: Evento expediente creado
activate Rabbit
deactivate Rabbit
activate Worker
Worker -> Worker: Ejecutar lógica de negocio
Worker -> WorkerDB: Save outbox event KO
activate WorkerDB
WorkerDB --> Worker: Saved
deactivate WorkerDB
deactivate Worker

group Event Dispatching
    WorkerEventDispatcher -> WorkerDB: Fetch outbox events
    activate WorkerEventDispatcher
    activate WorkerDB
    WorkerDB --> WorkerEventDispatcher: Outbox events
    deactivate WorkerDB
    WorkerEventDispatcher -> Rabbit: Publish Created OK
    activate Rabbit
    Rabbit --> WorkerEventDispatcher: Ack
    WorkerEventDispatcher -> WorkerDB: Mark outbox event as processed
    activate WorkerDB
    WorkerDB --> WorkerEventDispatcher: Updated
    deactivate WorkerEventDispatcher
    deactivate WorkerDB
end

Rabbit -> API: Evento expediente creado OK
deactivate Rabbit
activate API
API -> ApiDB: Delete expediente
activate ApiDB
ApiDB --> API: Deleted
deactivate ApiDB

API -> ApiDB: Save outbox event error
activate ApiDB
ApiDB --> API: Saved
deactivate ApiDB
deactivate API

group Event Dispatching
    ApiEventDispatcher -> ApiDB: Fetch outbox events
    activate ApiEventDispatcher
    activate ApiDB
    ApiDB --> ApiEventDispatcher: Outbox events
    deactivate ApiDB
    ApiEventDispatcher -> Kafka: Publish expediente alert
    activate Kafka
    Kafka --> ApiEventDispatcher: Ack
    deactivate Kafka
    ApiEventDispatcher -> ApiDB: Mark outbox event as processed
    activate ApiDB
    ApiDB --> ApiEventDispatcher: Updated
    deactivate ApiDB
    deactivate ApiEventDispatcher
end

== Procesamiento error creacion expediente ==

Kafka -> Worker: Consume Expediente Alert
Activate Kafka
deactivate Kafka
activate Worker
Worker -> Worker: Ejecutar lógica de negocio en error

@enduml