messaging.channels.rabbit.host=localhost
messaging.channels.rabbit.port=5672
messaging.channels.rabbit.username=admin
messaging.channels.rabbit.password=admin

# Consumidores
messaging.channels.creacion-expediente.type=rabbitmq
messaging.channels.creacion-expediente.queue=creacion-expediente-cola

# Productores
messaging.channels.creacion-expediente-ok.type=rabbitmq
messaging.channels.creacion-expediente-ok.exchange=expedientes
messaging.channels.creacion-expediente-ok.routing-key=creacion-ok

messaging.channels.creacion-expediente-ko.type=rabbitmq
messaging.channels.creacion-expediente-ko.exchange=expedientes
messaging.channels.creacion-expediente-ko.routing-key=creacion-ko
