messaging.channels.rabbitmq.host=localhost
messaging.channels.rabbitmq.port=5672
messaging.channels.rabbitmq.username=admin
messaging.channels.rabbitmq.password=admin

messaging.channels.kafka.bootstrap.servers=sample-kafka-broker:9092
messaging.channels.kafka.consumer-group=sample-worker-group

# Consumidores
messaging.channels.creacion-expediente.type=rabbitmq
messaging.channels.creacion-expediente.queue=creacion-expediente-cola

messaging.channels.creacion-expediente-alerta.type=kafka
messaging.channels.creacion-expediente-alerta.topic=creacion-expediente-alerta-topic
messaging.channels.creacion-expediente-alerta.consumer-group=creacion-expediente-alerta-group

# Productores
messaging.channels.creacion-expediente-ok.type=rabbitmq
messaging.channels.creacion-expediente-ok.exchange=expedientes
messaging.channels.creacion-expediente-ok.routing-key=creacion-ok

messaging.channels.creacion-expediente-ko.type=rabbitmq
messaging.channels.creacion-expediente-ko.exchange=expedientes
messaging.channels.creacion-expediente-ko.routing-key=creacion-ko
